services:
  - type: web
    name: skillgraph-api
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: COGNODB_URI
        sync: false
      - key: COGNODB_USERNAME
        sync: false
      - key: COGNODB_PASSWORD
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: PORT
        value: 5000
